# Generated by Django 2.2 on 2021-11-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
