# Generated by Django 2.2 on 2021-11-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_auto_20211106_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='thumnail',
        ),
    ]
