# Generated by Django 2.2 on 2021-11-21 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enroll', '0014_auto_20211106_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumnail',
            field=models.ImageField(blank=True, default='upload.png', upload_to=''),
        ),
    ]
