# Generated by Django 2.2 on 2021-11-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0018_auto_20211121_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
