# Generated by Django 2.2 on 2021-11-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0020_auto_20211124_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
