# Generated by Django 2.2 on 2021-11-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0022_auto_20211124_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
