# Generated by Django 2.2 on 2021-11-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0023_auto_20211126_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
