# Generated by Django 2.2 on 2021-11-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0027_auto_20211126_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
