# Generated by Django 2.2 on 2021-11-28 02:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enroll', '0028_auto_20211126_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Ticket',
        ),
    ]
