# Generated by Django 2.2 on 2021-12-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0030_ticketreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.DateTimeField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
