# Generated by Django 2.2 on 2021-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0035_auto_20211205_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
