# Generated by Django 2.2 on 2021-12-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0036_emailuser_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailUser',
        ),
    ]
